version: '3'
services:
    postgres:
        image: postgres:13
        env_file:
            - .env
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5
        restart: always


    scheduler:
        build: .
        command: scheduler
        restart: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/Users/eugene/Personal_Projects/Data_Project/app/airflow/dags
            - ./logs:/Users/eugene/Personal_Projects/Data_Project/app/airflow/logs
            - ./plugins:/Users/eugene/Personal_Projects/Data_Project/app/airflow/plugins
            - ./scripts:/Users/eugene/Personal_Projects/Data_Project/app/airflow/scripts
            - ~/.google/credentials/:/Users/eugene/.google/credentials


    webserver:
        build: . 
        entrypoint: ./scripts/entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/Users/eugene/Personal_Projects/Data_Project/app/airflow/dags
            - ./logs:/Users/eugene/Personal_Projects/Data_Project/app/airflow/logs
            - ./plugins:/Users/eugene/Personal_Projects/Data_Project/app/airflow/plugins
            - ./scripts:/Users/eugene/Personal_Projects/Data_Project/app/airflow/scripts
            - ~/.google/credentials/:/Users/eugene/.google/credentials:ro

        user: "${AIRFLOW_UID:-501}:0"
        ports:
            - "8080:8080"
        healthcheck:
            #test: [ "CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]" ]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
  postgres-db-volume: